apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nsenter
  name: nsenter
  namespace: monitoring
spec:
  containers:
  - command:
    - nsenter
    - --target
    - "1"
    - --mount
    - --uts
    - --ipc
    - --net
    - --pid
    - --
    - bash
    - -l
    env:
    - name: cluster
      value: $cluster
    - name: pvc
      value: $pvc
    image: docker.io/library/alpine
    imagePullPolicy: Always
    name: nsenter
    resources: {}
    securityContext:
      privileged: true
    stdin: true
    stdinOnce: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostNetwork: true
  hostPID: true
  nodeName: $node 
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
  - effect: NoExecute
    operator: Exists